---
 
- name: copy the template
  copy:
    src: "{{ oracle_tmp }}/database/response/db_install.rsp"
    dest: "{{ oracle_tmp }}/db_install.rsp"
    owner: "{{ oracle_user[0].name }}"
    group: "{{ oracle_group[0].name }"
    remote_src: yes

- name: set inline changes
  lineinfile: 
    path: /tmp/oracle/db_install.rsp
    regexp: "^{{ item.regex }}"
    line: "{{ item.regex }}={{ item.value }}"
  with_items:
    - { regex: oracle.install.responseFileVersion, value: "/oracle/install/rspfmt_dbinstall_response_schema_v11_2_0" }
    - { regex: oracle.install.option, value: "{{ install_mode }}" }
    - { regex: ORACLE_HOSTNAME, value: "{{ ansible_hostname }}" }
    - { regex: UNIX_GROUP_NAME, value: "{{ oracle_group[0].name }}" }
    - { regex: INVENTORY_LOCATION, value: "{{ oracle_base }}/oraInventory" }
    - { regex: SELECTED_LANGUAGES, value: "en" }
    - { regex: ORACLE_HOME, value: "{{ oracle_home }}" }
    - { regex: ORACLE_BASE, value: "{{ oracle_base }}" }
    - { regex: oracle.install.db.InstallEdition, value: "{{ oracle_edition }}" }
    - { regex: oracle.install.db.isCustomInstall, value: "false" }
    - { regex: oracle.install.db.DBA_GROUP, value: "{{ oracle_dba_group[0].name }}" }
    - { regex: oracle.install.db.OPER_GROUP, value: "{{ oracle_dba_group[0].name }}" }
    - { regex: oracle.install.db.config.starterdb.type, value: "GENERAL_PURPOSE" }
    - { regex: oracle.install.db.config.starterdb.globalDBName, value: "{{ oracle_db_name }}" }
    - { regex: oracle.install.db.config.starterdb.SID, value: "{{ oracle_db_name }}" }
    - { regex: oracle.install.db.config.starterdb.characterSet, value: "AL32UTF8" }
    - { regex: oracle.install.db.config.starterdb.memoryLimit, value: "{{ oracle_db_mem }}" }
    - { regex: oracle.install.db.config.starterdb.memoryOption, value: "true" }
    - { regex: oracle.install.db.config.starterdb.installExampleSchemas, value: "false" }
    - { regex: oracle.install.db.coableSecuritySettings, value: "true" }
    - { regex: oracle.install.db.config.starterdb.password.ALL, value: "{{ oracle_db_syspass }}" }
    - { regex: oracle.install.db.config.starterdb.storageType, value: "{{ oracle_storage_type }}" }
    - { regex: oracle.install.db.config.starterdb.fileSystemStorage.dataLocation, value: "{{ oracle_base }}/data" }